#version 450
#extension GL_EXT_shader_explicit_arithmetic_types_float16 : require

layout(local_size_x = 64) in;

layout(set = 0, binding = 0) buffer OutBuffer {
    uint outData[];
};

void main() {
    uint gid = gl_GlobalInvocationID.x;
    float16_t a = float16_t(float((gid & 255u) + 1u) * 0.5);
    float16_t b = float16_t(float(((gid * 5u) & 255u) + 3u) * 0.25);
    float c = float(a + b * float16_t(0.75));
    outData[gid] = floatBitsToUint(c);
}
