/*
 * SASS RE Probe: Hierarchical/Multi-Level Tiling
 * Isolates: L1 tile inside L2 tile, register tile inside smem tile
 *
 * Production GPU kernels often use nested tiling:
 *   Level 1: Thread block tile (fits in L2)
 *   Level 2: Warp tile within block (fits in smem)
 *   Level 3: Thread tile within warp (fits in registers)
 *
 * This probe tests the SASS generated by each nesting level.
 */

// 3-level hierarchical GEMM: block 128x128, warp 32x32, thread 4x4
extern "C" __global__ void __launch_bounds__(256)
probe_tile_hierarchical_gemm(float *C, const float *A, const float *B,
                              int M, int N, int K) {
    // Block tile: 128x128 output
    // Warp tile: 32x32 (8 warps per block, 4x2 warp grid)
    // Thread tile: 4x4 (each thread computes 4x4 output elements)
    __shared__ float sA[128][8];  // 128 rows x 8 columns of A per K-step
    __shared__ float sB[8][128];  // 8 rows x 128 columns of B per K-step

    int warp_id = threadIdx.x / 32;
    int lane = threadIdx.x % 32;

    int warp_row = (warp_id / 2) * 32;
    int warp_col = (warp_id % 2) * 64;

    // Thread tile position within warp tile
    int trow = (lane / 8) * 4;
    int tcol = (lane % 8) * 4;

    int grow = blockIdx.y * 128 + warp_row + trow;
    int gcol = blockIdx.x * 128 + warp_col + tcol;

    // Thread-level accumulators (4x4 = 16 registers)
    float acc[4][4];
    #pragma unroll
    for (int i = 0; i < 4; i++)
        for (int j = 0; j < 4; j++)
            acc[i][j] = 0.0f;

    // K-loop: process 8 columns of A / rows of B per iteration
    for (int kk = 0; kk < K; kk += 8) {
        // Cooperative load of A tile (128x8)
        int load_row = threadIdx.x / 8;
        int load_col = threadIdx.x % 8;
        if (blockIdx.y * 128 + load_row < M && kk + load_col < K)
            sA[load_row][load_col] = A[(blockIdx.y * 128 + load_row) * K + kk + load_col];
        else
            sA[load_row][load_col] = 0.0f;

        // Cooperative load of B tile (8x128)
        int load_r = threadIdx.x / 128;
        int load_c = threadIdx.x % 128;
        if (kk + load_r < K && blockIdx.x * 128 + load_c < N)
            sB[load_r][load_c] = B[(kk + load_r) * N + blockIdx.x * 128 + load_c];
        else if (load_r < 8)
            sB[load_r][load_c] = 0.0f;

        __syncthreads();

        // Thread tile: 4x4 matmul from smem
        #pragma unroll
        for (int k = 0; k < 8; k++) {
            float a[4], b[4];
            #pragma unroll
            for (int i = 0; i < 4; i++)
                a[i] = sA[warp_row + trow + i][k];
            #pragma unroll
            for (int j = 0; j < 4; j++)
                b[j] = sB[k][warp_col + tcol + j];
            #pragma unroll
            for (int i = 0; i < 4; i++)
                #pragma unroll
                for (int j = 0; j < 4; j++)
                    acc[i][j] = fmaf(a[i], b[j], acc[i][j]);
        }
        __syncthreads();
    }

    // Write 4x4 tile to global
    #pragma unroll
    for (int i = 0; i < 4; i++)
        #pragma unroll
        for (int j = 0; j < 4; j++)
            if (grow + i < M && gcol + j < N)
                C[(grow + i) * N + gcol + j] = acc[i][j];
}

// 2-level tile: smem tile + register tile for 1D convolution
extern "C" __global__ void __launch_bounds__(256)
probe_tile_2level_conv(float *out, const float *in,
                        const float *kernel_weights, int n, int ksize) {
    extern __shared__ float smem[];
    int tid = threadIdx.x;
    int half_k = ksize / 2;

    // Level 1: load tile + halo into shared memory
    int smem_size = blockDim.x + ksize - 1;
    for (int i = tid; i < smem_size; i += blockDim.x) {
        int gi = blockIdx.x * blockDim.x + i - half_k;
        smem[i] = (gi >= 0 && gi < n) ? in[gi] : 0.0f;
    }
    __syncthreads();

    // Level 2: each thread computes 1 output (register accumulation)
    int gx = blockIdx.x * blockDim.x + tid;
    if (gx < n) {
        float acc = 0.0f;
        #pragma unroll
        for (int k = 0; k < ksize; k++)
            acc = fmaf(kernel_weights[k], smem[tid + k], acc);
        out[gx] = acc;
    }
}

// Recursive halving tile (reduction pattern with shrinking tile)
extern "C" __global__ void __launch_bounds__(512)
probe_tile_recursive_half(float *out, const float *in, int n) {
    __shared__ float s[512];
    int tid = threadIdx.x;
    int gid = blockIdx.x * 512 + tid;
    s[tid] = (gid < n) ? in[gid] : 0.0f;
    __syncthreads();

    // Recursive halving: each step halves the active tile
    for (int size = 256; size > 0; size >>= 1) {
        if (tid < size)
            s[tid] += s[tid + size];
        __syncthreads();
    }

    if (tid == 0) out[blockIdx.x] = s[0];
}
