#version 450

layout(local_size_x = 64, local_size_y = 1, local_size_z = 1) in;

layout(std430, binding = 0) buffer OutputBuffer {
    float values[];
} outbuf;
#extension GL_ARB_gpu_shader_int64 : require

void main(void) {
    uint index = gl_GlobalInvocationID.x;
    int64_t acc = int64_t(index) - int64_t(31);
    for (int i = 0; i < 512; ++i) {
        acc = acc + int64_t(3);
    }
    outbuf.values[index] = float(acc & int64_t(0xffff));
}
