#version 450

layout(local_size_x = 64, local_size_y = 1, local_size_z = 1) in;

layout(std430, binding = 0) buffer OutputBuffer {
    float values[];
} outbuf;

int sign_extend24(int value) {
    return (value << 8) >> 8;
}

void main(void) {
    uint index = gl_GlobalInvocationID.x;
    int acc = sign_extend24(int(index * 13u) - 0x00300000);

    for (int i = 0; i < 512; ++i) {
        acc = sign_extend24(acc * 3 - 7);
    }

    outbuf.values[index] = float(acc) * (1.0 / 8388608.0);
}
